### ISSUE TITLE
Multisite using folder (subdirectory multi-site)

### ISSUE THREAD

**Issue by sumachaa** [platformsh-templates/drupal8-multisite#24]
The example shows how to setup the multisite using subdomain
How can we do this using one domain & with folders (subdirectories)

www.example.com
www.example.com/site2
www.example.com/site3

D7 example would be this
https://www.drupal.org/docs/7/multisite-drupal/multi-site-in-subdirectories

**Comment by hugronaphor** [comment]
You would need to get your hands on Nginx config file to be able to achieve it.
Don't think platform allows this.

PS: While this is what board thinks they want, from tech perspective is somehow hard to implement and better go with domains/subdomains.

**Comment by darthsteven** [comment]
I _feel_ like this should be possible because platform.sh has documentation for running multiple apps from subdirectories.

I need to be able to do this for a project I'm working on. I'll try to remember to post here if I get any results!

**Comment by darthsteven** [comment]
Yeah, so I was able to get this working by tweaking the `.platform.app.yaml` file to have additional locations.

So take this:

```yaml
# The configuration of app when it is exposed to the web.
web:
    locations:
        # All requests not otherwise specified follow these rules.
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'


            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m


            # Redirect any incoming request to Drupal's front controller.
            passthru: '/index.php'


            # Deny access to all static files, except those specifically allowed below.
            allow: false


            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true


                # Deny direct access to configuration files.
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false


        # The files directory has its own special configuration rules.
        '/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/files'


            # Do not execute PHP scripts from the writeable mount.
            scripts: false


            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/files/(css|js)':
                    expires: 2w
```

And make it something like this:

```yaml
# The configuration of app when it is exposed to the web.
web:
    locations:
        # Copy of the base '/' location, with some tweaks for the subsite.
        '/subsite1':
            root: 'web'
            expires: 5m
            # Prepend the subsite1 folder to the controller passthru.
            passthru: '/subsite1/index.php'
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false

        # All requests not otherwise specified follow these rules.
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'


            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m


            # Redirect any incoming request to Drupal's front controller.
            passthru: '/index.php'


            # Deny access to all static files, except those specifically allowed below.
            allow: false


            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true


                # Deny direct access to configuration files.
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false


        # The files directory has its own special configuration rules.
        '/files':
            # Allow access to all files in the public files directory.
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/files'


            # Do not execute PHP scripts from the writeable mount.
            scripts: false


            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/files/(css|js)':
                    expires: 2w
```

Which seems to be sort of mostly working, some rough edges, but I think this approach is sound.
